### ISSUE TITLE
Issue with Satriani

### ISSUE THREAD

**Issue by hopppz** [RockstarLang/rockstar#229]
Hoping this is the best place to ask.

I'm trying to run Satriani from the command line

I followed the steps in the read me 

When I pass node rockstar input.rock

I get the following error.

``throw err;
    ^

Error: Cannot find module 'readline-sync'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/matt/Documents/rockstar/satriani/rockstar.js:3:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
``

I'm aware readline-sync is a module of npm so I made sure I had it installed and updated and I do not sure how to progress this.

**Comment by dylanbeattie** [comment]
Hey,

Try opening the `rockstar/satriani` folder in a terminal and running

```
yarn install
yarn test
```

That should install the necessary dependencies and run the test suite. If it doesn't work, follow up here and we'll see if we can work out what's happening. Thanks!
